### PR TITLE
A fix to issue #1

### PR DESCRIPTION
**Pull request by mromanello**
Fixes the problem described in [issue 1](https://github.com/PonteIneptique/surfrdf/issues/1). I tested the `sparql_protocol` plugin against an existing Virtuoso triple store.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Could you add a test for this particular case ? A really simple one ?
I am wondering if the line could actually be `if isinstance(list, tuple) and not isinstance(group)` and if it'd work.

**Comment by mromanello** [comment]
> Could you add a test for this particular case ? A really simple one ?

The problem is that `surf` does not include tests against a real triple store, but it mocks one instead. So, I'm not sure whether this can be tested within `surf` as it is right now. However, in the long run it'd be desirable to add such tests, which includes also setting up a triple store in Travis (but I'm doing it already anyway for `hucitlib` so I could reuse the code).

**Comment by PonteIneptique** [comment]
> The problem is that `surf` does not include tests against a real triple store, but it mocks one instead

You could have RDFLib memory triple store for that no ?

Anyway, that's for another issue maybe. I'd like to know first if things will work in py3 ;)

**Comment by mromanello** [comment]
thanks for merging! btw, I've tested your solution `isinstance(list, tuple) and not isinstance(group)` and that works fine too.

**Pull request merged**
